### ISSUE TITLE
computed使用疑惑

### ISSUE THREAD

**Issue by Juliiii** [web-infra-dev/reduck#105]
看官方文档，感觉在强调，衍生状态依赖的值是本身的State或者别的Model的State。
但在业务开发中，有个场景是，衍生状态依赖的值是本身的衍生状态，或者别的Model的衍生状态。
这个场景下，请问是否有潜在风险呢？目前看源码感觉是有概率出现的？

**Comment by xuchaobei** [comment]
可以具体说下潜在风险指什么？最好能有个 demo 哈

**Comment by Juliiii** [comment]
你好！我已经收到你的邮件，我会尽快回复你的~
